-- SISTEMA DE PROVA INFORMATIZADO
--Andrey Reis Villanetti  n°02
--Gabriel Rodrigues de Jesus Guedes n°08
--julia Marques de Oliveira Silva n°18
--Marcos Paulo Soares Silva n°24
--Rodri  Trajano da Silva n°31
--Thamires Santana Teixera  n°33 
-- INF3DM


   


CREATE DATABASE SistemaP;
 go
  use SistemaP;


 
CREATE LOGIN equipe7   
    WITH PASSWORD = '123456';  



CREATE USER equipe7 FOR LOGIN equipe7
    WITH DEFAULT_SCHEMA = db_owner;  

	
GRANT ALL PRIVILEGES TO EQUIPE7;

drop table SistemaP.DBO.TB_MATERIA
 
drop table SistemaP.DBO.TBnotas_aluno
  
drop table SistemaP.DBO.TBPROVA 
 
drop table SistemaP.DBO.TBQUESTAO 
 
drop table SistemaP.DBO.TB_STATUS
  
drop table SistemaP.DBO.TBPROVA_QUESTAO 
 
drop table SistemaP.DBO.PROF_MATERIA
  
drop table SistemaP.DBO.TB_PROF 
 
drop table SistemaP.DBO.TB_ALUNO

drop table SistemaP.DBO.TB_TURMA
 
drop table SistemaP.DBO.TB_ADMIN

 drop table SistemaP.DBO.TB_USER

drop table SistemaP.DBO.TB_NIVELDEACESSO 


DROP SEQUENCE SistemaP.DBO.SEQ_QUESTAO
  
DROP SEQUENCE SistemaP.DBO.SEQ_PROVA 
 
DROP SEQUENCE SistemaP.DBO.SEQ_QUESTAO 
  
DROP SEQUENCE SistemaP.DBO.SEQ_MATERIA 



CREATE TABLE SistemaP.DBO.TB_MATERIA
(

ID_MATERIA INTEGER NOT NULL PRIMARY KEY,
STATUS INTEGER,
MATERIA_PROF VARCHAR(30) NOT NULL 
);
 
CREATE TABLE SistemaP.DBO.TB_NIVELDEACESSO(
ID_ACESSO INTEGER NOT NULL  PRIMARY KEY,
NIVELACESSO VARCHAR(15) NOT NULL 
);
 
CREATE TABLE SistemaP.DBO.TB_TURMA
(

ID_TURMA INTEGER NOT NULL PRIMARY KEY,
TURMA_ALU VARCHAR(15) NOT NULL UNIQUE,
STATUS INTEGER
);
 


CREATE TABLE SistemaP.DBO.TB_STATUS
(
STATUS INTEGER NOT NULL PRIMARY KEY,
NOME_STATUS VARCHAR(10)
);
 
CREATE TABLE SistemaP.DBO.TB_USER
  (
LOGIN VARCHAR(20 ) NOT NULL , 
SENHA VARCHAR(40 ) NOT NULL , 
ID_ACESSO INTEGER NOT NULL, 
status integer,
CONSTRAINT PK_USER PRIMARY KEY (LOGIN),
CONSTRAINT PK_NIVELACESSO FOREIGN KEY (ID_ACESSO)
REFERENCES SistemaP.DBO.TB_NIVELDEACESSO (ID_ACESSO) 
);
   
CREATE TABLE SistemaP.DBO.TB_ADMIN
(
RM_ADMIN INTEGER NOT NULL , 
LOGIN VARCHAR(20) , 
NOME VARCHAR(50 ) NOT NULL , 
ULTIMOACESSO DATE, 
STATUS INTEGER, 
CADASTRO DATE, 
CONSTRAINT  PK_TB_ADMIN PRIMARY KEY(RM_ADMIN),
CONSTRAINT FK_TB_ADMIN FOREIGN KEY (LOGIN)
REFERENCES SistemaP.DBO.TB_USER(LOGIN) 
);
 

CREATE TABLE SistemaP.DBO.TB_ALUNO
(
RM_ALUNO INTEGER NOT NULL PRIMARY KEY,	
ID_TURMA INTEGER ,
NUM_CHAMADA INTEGER NOT NULL ,
LOGIN VARCHAR(20),
NOME VARCHAR(50) NOT NULL ,
ULTIMOACESSO DATE,
STATUS INTEGER,
CADASTRO DATE,
CONSTRAINT FK_TB_ALUNO FOREIGN KEY(LOGIN)
REFERENCES SistemaP.DBO.TB_USER(LOGIN),

CONSTRAINT FK_TB_ALUNO_ID_TURMA FOREIGN KEY(ID_TURMA)  
REFERENCES SistemaP.DBO.TB_TURMA(ID_TURMA)
); 

CREATE TABLE SistemaP.DBO.TB_PROF
(
RM_PROFESSOR INTEGER PRIMARY KEY,
LOGIN VARCHAR(20),
NOME VARCHAR(50)NOT NULL ,                     
ULTIMOACESSO DATE,
STATUS INTEGER,
CADASTRO DATE,

CONSTRAINT FK_TB_PROF FOREIGN KEY(LOGIN)
REFERENCES SistemaP.DBO.TB_USER(LOGIN)


); 

CREATE TABLE SistemaP.DBO.PROF_MATERIA
(


RM_PROFESSOR INT NOT NULL,
MATERIA_PROF VARCHAR(30)


); 

CREATE TABLE SistemaP.DBO.TBPROVA
(
IDPROVA INTEGER NOT NULL PRIMARY KEY,
PROVA VARCHAR(30) NOT NULL,
MATERIA_PROVA VARCHAR(30) NOT NULL,
etiqueta varchar(40),
Quantidade integer,
NOME_PROF VARCHAR(50)NOT NULL ,
turmaatual VARCHAR(20) null,
STATUS INTEGER

); 



CREATE TABLE SistemaP.DBO.TBQUESTAO
(
IDQUESTAO INTEGER NOT NULL PRIMARY KEY,
STATUS INTEGER,
TITULO VARCHAR(30),
MATERIA VARCHAR(50) NOT NULL,
ETIQUETA VARCHAR(20) NOT NULL,
QUESTAO VARCHAR(500) NOT NULL,
RESPOSTAA VARCHAR(200) NOT NULL,
RESPOSTAB VARCHAR(200) NOT NULL,
RESPOSTAC VARCHAR(200) NOT NULL,
RESPOSTAD VARCHAR(200) NOT NULL,
RESPOSTACERTA VARCHAR(200) NOT NULL,
RM_PROFESSOR INTEGER NOT NULL

);
 


CREATE TABLE SistemaP.DBO.TBPROVA_QUESTAO
(

IDPROVA INTEGER,
IDQUESTAO INTEGER



); 

CREATE TABLE SistemaP.DBO.TBNOTAS_ALUNO
(
RM_ALUNO INTEGER,
PROVA VARCHAR(200) ,
NOTA VARCHAR(100),

idprova integer,

);
 


CREATE SEQUENCE SEQ_MATERIA

START WITH 1
INCREMENT BY 1
NO CACHE
NO CYCLE;
 

CREATE SEQUENCE SEQ_TURMA
START WITH 1
INCREMENT BY 1
NO CACHE
NO CYCLE;
 

CREATE SEQUENCE SEQ_QUESTAO
START WITH 1
INCREMENT BY 1
NO CACHE
NO CYCLE;
 

CREATE SEQUENCE SEQ_PROVA
START WITH 1
INCREMENT BY 1
NO CACHE
NO CYCLE;
 

CREATE SEQUENCE SEQ_PROVA2
START WITH 1
INCREMENT BY 1
NO CACHE
NO CYCLE;
 

INSERT SistemaP.DBO.TB_STATUS VALUES ('1','ativo');
  
INSERT SistemaP.DBO.TB_STATUS VALUES ('0','inativo');
 


INSERT SistemaP.DBO.TB_NIVELDEACESSO VALUES ('1','administrador');
INSERT SistemaP.DBO.TB_NIVELDEACESSO VALUES ('2','professor');
INSERT SistemaP.DBO.TB_NIVELDEACESSO VALUES ('3','aluno');



INSERT SistemaP.DBO.TB_MATERIA (ID_MATERIA, MATERIA_PROF, STATUS)VALUES (next value for SistemaP.DBO.SEQ_MATERIA,'LIP1',1);
INSERT SistemaP.DBO.TB_MATERIA(ID_MATERIA, MATERIA_PROF, STATUS) VALUES (next value for SistemaP.DBO.SEQ_MATERIA,'LIP2',1);
INSERT SistemaP.DBO.TB_MATERIA(ID_MATERIA, MATERIA_PROF, STATUS) VALUES (next value for SistemaP.DBO.SEQ_MATERIA,'ASOO',1);
INSERT SistemaP.DBO.TB_MATERIA (ID_MATERIA, MATERIA_PROF, STATUS)VALUES (next value for SistemaP.DBO.SEQ_MATERIA,'ESMD',1);
INSERT SistemaP.DBO.TB_MATERIA(ID_MATERIA, MATERIA_PROF, STATUS) VALUES (next value for SistemaP.DBO.SEQ_MATERIA,'LIEC',1);
INSERT SistemaP.DBO.TB_MATERIA (ID_MATERIA, MATERIA_PROF, STATUS)VALUES (next value for SistemaP.DBO.SEQ_MATERIA,'BADA',1);
INSERT SistemaP.DBO.TB_MATERIA (ID_MATERIA, MATERIA_PROF, STATUS)VALUES (next value for SistemaP.DBO.SEQ_MATERIA,'TEEM',1);
INSERT SistemaP.DBO.TB_MATERIA (ID_MATERIA, MATERIA_PROF, STATUS)VALUES (next value for SistemaP.DBO.SEQ_MATERIA,'ARCO',1);
INSERT SistemaP.DBO.TB_MATERIA(ID_MATERIA, MATERIA_PROF, STATUS) VALUES (next value for SistemaP.DBO.SEQ_MATERIA,'TEIN',1);

INSERT SistemaP.DBO.TB_TURMA (ID_TURMA, TURMA_ALU, STATUS)VALUES (next value for SistemaP.DBO.SEQ_TURMA,' INF1B ',1);
INSERT SistemaP.DBO.TB_TURMA VALUES (next value for SistemaP.DBO.SEQ_TURMA,'INF1A',1);
INSERT SistemaP.DBO.TB_TURMA VALUES (next value for SistemaP.DBO.SEQ_TURMA,'INF1B',1);
INSERT SistemaP.DBO.TB_TURMA VALUES (next value for SistemaP.DBO.SEQ_TURMA,'INF1C',1);
INSERT SistemaP.DBO.TB_TURMA VALUES (next value for SistemaP.DBO.SEQ_TURMA,'INF1D',1);
INSERT SistemaP.DBO.TB_TURMA VALUES (next value for SistemaP.DBO.SEQ_TURMA,'INF1E',1);
INSERT SistemaP.DBO.TB_TURMA VALUES (next value for SistemaP.DBO.SEQ_TURMA,'INF1F',1);
INSERT SistemaP.DBO.TB_TURMA VALUES (next value for SistemaP.DBO.SEQ_TURMA,'INF1G',1);
INSERT SistemaP.DBO.TB_TURMA VALUES (next value for SistemaP.DBO.SEQ_TURMA,'INF1H',1);
INSERT SistemaP.DBO.TB_TURMA VALUES (next value for SistemaP.DBO.SEQ_TURMA,'INF2A',1);
INSERT SistemaP.DBO.TB_TURMA VALUES (next value for SistemaP.DBO.SEQ_TURMA,'INF2B',1);
INSERT SistemaP.DBO.TB_TURMA VALUES (next value for SistemaP.DBO.SEQ_TURMA,'INF2C',1);
INSERT SistemaP.DBO.TB_TURMA VALUES (next value for SistemaP.DBO.SEQ_TURMA,'INF2D',1);
INSERT SistemaP.DBO.TB_TURMA VALUES (next value for SistemaP.DBO.SEQ_TURMA,'INF2E',1);
INSERT SistemaP.DBO.TB_TURMA VALUES (next value for SistemaP.DBO.SEQ_TURMA,'INF2F',1);
INSERT SistemaP.DBO.TB_TURMA VALUES (next value for SistemaP.DBO.SEQ_TURMA,'INF2G',1);
INSERT SistemaP.DBO.TB_TURMA VALUES (next value for SistemaP.DBO.SEQ_TURMA,'INF2H',1);
INSERT SistemaP.DBO.TB_TURMA VALUES (next value for SistemaP.DBO.SEQ_TURMA,'INF3A',1);
INSERT SistemaP.DBO.TB_TURMA VALUES (next value for SistemaP.DBO.SEQ_TURMA,'INF3B',1);
INSERT SistemaP.DBO.TB_TURMA VALUES (next value for SistemaP.DBO.SEQ_TURMA,'INF3C',1);
INSERT SistemaP.DBO.TB_TURMA VALUES (next value for SistemaP.DBO.SEQ_TURMA,'INF3D',1);
INSERT SistemaP.DBO.TB_TURMA VALUES (next value for SistemaP.DBO.SEQ_TURMA,'INF3E',1);
INSERT SistemaP.DBO.TB_TURMA VALUES (next value for SistemaP.DBO.SEQ_TURMA,'INF3F',1);
INSERT SistemaP.DBO.TB_TURMA VALUES (next value for SistemaP.DBO.SEQ_TURMA,'INF3G',1);
INSERT SistemaP.DBO.TB_TURMA VALUES (next value for SistemaP.DBO.SEQ_TURMA,'INF3H',1);
INSERT  SistemaP.DBO.TB_USER VALUES ('ADM_98765','987','1','1');

INSERT SistemaP.DBO.TB_ADMIN ( RM_ADMIN  , 	LOGIN ,  NOME  , ULTIMOACESSO , STATUS , CADASTRO  )
VALUES ('98765','ADM_98765','ADM','26/09/2017','1','26/09/2017' );
-------------------------------------------------------------------------
INSERT SistemaP.DBO.TB_USER VALUES ('PROF_98765','987','2','1');

INSERT SistemaP.DBO.TB_PROF ( rm_professor  , LOGIN ,  NOME  , ULTIMOACESSO , STATUS , CADASTRO  )
VALUES ('98765','PROF_98765','PROF','26/09/2017','1','26/09/2017' );
-------------------------------------------------------------------------
INSERT  SistemaP.DBO.TB_user VALUES ('ALU_98765','987','3','1');

INSERT  SistemaP.DBO.TB_ALUNO ( RM_ALUNO, ID_TURMA, NUM_CHAMADA, LOGIN, NOME , ULTIMOACESSO, STATUS, CADASTRO)
VALUES ('98765','2','00','ALU_98765','ALU','26/09/2017','1','26/09/2017' );
------------------------------------------------------------------------

select * from TB_USER
INSERT INTO [dbo].[TBQUESTAO]

([IDQUESTAO],[STATUS],[TITULO],[MATERIA],[ETIQUETA],[QUESTAO],[RESPOSTAA],[RESPOSTAB],[RESPOSTAC],[RESPOSTAD],[RESPOSTACERTA] ,[RM_PROFESSOR])

 VALUES
           (next value for seq_questao, 1, 'QUESTAO 1','LIP2','CONEXÃO BD','Qual método se usa para executar uma ação de insert, alter ou delete do C# para o BD?','fill','execute','Start','Execute','ExecuteNonQuery','98765')
GO


INSERT INTO [dbo].[TBQUESTAO]

([IDQUESTAO],[STATUS],[TITULO],[MATERIA],[ETIQUETA],[QUESTAO],[RESPOSTAA],[RESPOSTAB],[RESPOSTAC],[RESPOSTAD],[RESPOSTACERTA] ,[RM_PROFESSOR])

 VALUES
           (next value for seq_questao, 1, 'QUESTAO 2','LIP2','FORMULÁRIO','QUAL DAS ALTERNATIVAS A SEGUIR NOS DÁ A FORMA CERTA DE CHAMAR UM FORMULÁRIO?','Form f = new Form(); f.ShowDialog()','Form f = new Form(); f.Show();',' new Form f =  Form(); f.ShowDialog();','Form f = new Form(); f.Dialog();','Form f = new Form(); f.ShowDialog();','98765')
GO


INSERT INTO [dbo].[TBQUESTAO]

([IDQUESTAO],[STATUS],[TITULO],[MATERIA],[ETIQUETA],[QUESTAO],[RESPOSTAA],[RESPOSTAB],[RESPOSTAC],[RESPOSTAD],[RESPOSTACERTA] ,[RM_PROFESSOR])

 VALUES
           (next value for seq_questao, 1, 'QUESTAO 3','LIP2','TIPO DE DADO','SELECIONE O TIPO DE DADO APROPRIADO PARA O VALOR A SEGUIR: HELLO WORD!','INT','DOUBLE','BOOL','FLOAT','STRING','98765')
GO


INSERT INTO [dbo].[TBQUESTAO]

([IDQUESTAO],[STATUS],[TITULO],[MATERIA],[ETIQUETA],[QUESTAO],[RESPOSTAA],[RESPOSTAB],[RESPOSTAC],[RESPOSTAD],[RESPOSTACERTA] ,[RM_PROFESSOR])

 VALUES
           (next value for seq_questao, 1, 'QUESTAO 4','LIP2','TIPO DE DADO','SELECIONE O TIPO DE DADO APROPRIADO PARA O VALOR A SEGUIR: 2,33','INT','STRING','BOOL','VAR','DOUBLE','98765')
GO


INSERT INTO [dbo].[TBQUESTAO]

([IDQUESTAO],[STATUS],[TITULO],[MATERIA],[ETIQUETA],[QUESTAO],[RESPOSTAA],[RESPOSTAB],[RESPOSTAC],[RESPOSTAD],[RESPOSTACERTA] ,[RM_PROFESSOR])

 VALUES
           (next value for seq_questao, 1, 'QUESTAO 5','LIP2','OPERADORES','QUAL O OPERADOR QUE SE UTILIZA PARA SOMAR VALORES?','-','/','*','^','+','98765')
GO



select * from SistemaP.dbo.tbprova

INSERT INTO [dbo].[TBPROVA]
           ([IDPROVA],[PROVA],[MATERIA_PROVA],[etiqueta],[Quantidade],[NOME_PROF],[turmaatual],[STATUS])
     VALUES
           (next value for seq_prova,'PROVA MENSAL 2º TRI','LIP2','DADOS E CONEXÕES','4','PROF','----','1')
GO

insert into SistemaP.dbo.TBPROVA_QUESTAO values(6,5);

insert into SistemaP.dbo.TBPROVA_QUESTAO values(6,6);

insert into SistemaP.dbo.TBPROVA_QUESTAO values(6,7);


insert into SistemaP.dbo.TBPROVA_QUESTAO values(6,8);

INSERT INTO [dbo].[TBPROVA]
           ([IDPROVA],[PROVA],[MATERIA_PROVA],[etiqueta],[Quantidade],[NOME_PROF],[turmaatual],[STATUS])
     VALUES
           (next value for seq_prova,'PROVA MENSAL 3º TRI','LIP2','DADOS ','2','PROF','----','1')
GO


select * from SistemaP.dbo.tbquestao

